// quizScore/quizTotal: best attempt. null = not attempted. quizReady false = no quiz yet.
export const BABS = [
  {
    n: 1,
    emoji: '🏛️',
    title: 'Warisan Negara Bangsa',
    short: 'Kerajaan Alam Melayu & warisan budaya',
    accent: '#52b396',
    accentLight: 'rgba(82,179,150,0.14)',
    label: '#315649',
    quizReady: true,
    quizScore: 4,
    quizTotal: 5,
  },
  {
    n: 2,
    emoji: '🔥',
    title: 'Kebangkitan Nasionalisme',
    short: 'Idea nasionalisme di Asia & Tanah Melayu',
    accent: '#5887ce',
    accentLight: 'rgba(88,135,206,0.14)',
    label: '#294d80',
    quizReady: false,
    quizScore: null,
    quizTotal: null,
  },
  {
    n: 3,
    emoji: '🌍',
    title: 'Konflik Dunia & Pendudukan Jepun',
    short: 'PKII, Jepun & perjuangan rakyat',
    accent: '#788a9c',
    accentLight: 'rgba(120,138,156,0.14)',
    label: '#41576c',
    quizReady: false,
    quizScore: null,
    quizTotal: null,
  },
  {
    n: 4,
    emoji: '⚖️',
    title: 'Era Peralihan Kuasa British',
    short: 'BMA, Malayan Union & reaksi rakyat',
    accent: '#627ea8',
    accentLight: 'rgba(98,126,168,0.14)',
    label: '#465d77',
    quizReady: true,
    quizScore: null,
    quizTotal: 5,
  },
  {
    n: 5,
    emoji: '🤝',
    title: 'Persekutuan Tanah Melayu 1948',
    short: 'Penubuhan, faktor & ciri utama',
    accent: '#4a847c',
    accentLight: 'rgba(74,132,124,0.14)',
    label: '#315f57',
    quizReady: false,
    quizScore: null,
    quizTotal: null,
  },
  {
    n: 6,
    emoji: '🛡️',
    title: 'Ancaman Komunis & Darurat',
    short: 'Komunis, darurat & usaha mengatasinya',
    accent: '#844646',
    accentLight: 'rgba(132,70,70,0.14)',
    label: '#6f3e3e',
    quizReady: false,
    quizScore: null,
    quizTotal: null,
  },
  {
    n: 7,
    emoji: '🕊️',
    title: 'Usaha ke Arah Kemerdekaan',
    short: 'Kerjasama kaum & jalan kemerdekaan',
    accent: '#6a58aa',
    accentLight: 'rgba(106,88,170,0.14)',
    label: '#584892',
    quizReady: false,
    quizScore: null,
    quizTotal: null,
  },
];
